"""Corrected NEC baseline: regime-conditional mixture-of-experts.

Design spec: ``NEC_sources/NEC_baseline_design.md`` (project root). The gate is
a shared expert-likelihood core plus a pluggable RegimePrior, so both candidate
thesis variations — the routing-mechanism comparison and the HMM-gated NEC —
are config choices over one skeleton.
"""

from .alignment import (
    ExpertAlignment,
    RegimeAlignmentReport,
    gate_regime_alignment,
    gate_utilization_by_date,
    regime_alignment,
)
from .base import BaseCache, BaseFit, BaseModel, base_cache_key, fit_base
from .baselines import BaselineModel, MLPBaseline, RidgeBaseline
from .calibration import (
    ReliabilityReport,
    TemperatureFit,
    fit_temperature,
    gate_reliability,
)
from .config import (
    BaseConfig,
    DataConfig,
    EncoderConfig,
    ExpertConfig,
    GateConfig,
    NECConfig,
    PriorConfig,
    TrainConfig,
    pyramid_dims,
)
from .context_data import build_context, load_french_factors, load_vix
from .data import (
    Batch,
    FeatureSchema,
    Panel,
    PanelData,
    SyntheticPanel,
    SyntheticRegimePanel,
    SyntheticSpec,
)
from .evaluation import (
    FoldResult,
    IcSummary,
    PortfolioSummary,
    WalkForwardFold,
    WalkForwardResult,
    base_and_correction,
    ic_summary,
    long_short_by_date,
    portfolio_summary,
    rank_ic_by_date,
    walk_forward_evaluate,
    walk_forward_evaluate_baseline,
    walk_forward_folds,
)
from .experts import (
    EMISSION_REGISTRY,
    ClassicalGaussianEmission,
    Emission,
    ExpertBank,
    build_emission,
)
from .features import (
    SEQUENCE_FEATURES,
    SNAPSHOT_FEATURES,
    StageBSpec,
    build_panel,
    build_stage_b_panel,
    data_config_from_panel,
    rolling_beta,
)
from .likelihood import expert_log_likelihood
from .losses import (
    LoadBalanceBuffer,
    MixtureNLLOutput,
    correction_penalty_aux,
    expert_decorrelation_aux,
    load_balance_aux,
    mixture_nll,
)
from .market_data import DEFAULT_UNIVERSE, MARKET_SYMBOL, load_ohlcv, load_universe
from .model import NECModel, NECOutput
from .multiple_testing import (
    DeflatedSharpe,
    benjamini_hochberg,
    bonferroni,
    deflated_sharpe_ratio,
    expected_max_sharpe,
    ic_pvalue,
    probabilistic_sharpe_ratio,
    sharpe_ratio,
)
from .networks import ACTIVATION_REGISTRY, MLPBlock, build_activation
from .plots import (
    plot_gate_utilization,
    plot_ic_series,
    plot_long_short_curve,
    plot_reliability,
    plot_sweep_report,
    plot_training_dashboard,
    plot_transition_matrix,
)
from .priors import (
    PRIOR_REGISTRY,
    GumbelSoftmaxRegimePrior,
    HardRegimePrior,
    HMMRegimePrior,
    PriorContext,
    PriorOutput,
    RegimePrior,
    Router,
    SoftRegimePrior,
    TopKRegimePrior,
    UniformRegimePrior,
    build_prior,
)
from .registry import TrialRecord, TrialRegistry
from .sweep import (
    ArmSummary,
    SweepArm,
    SweepReport,
    baseline_arm,
    corrected_claims,
    nec_arm,
    run_sweep,
)
from .train import DeadParameterWarning, GradientAudit, SequenceEval, Trainer
from .tuning import TuneResult, tune, validation_tail
from .universe import (
    PointInTimeUniverse,
    filter_point_in_time,
    load_sp500_universe,
    universe_coverage_report,
)
from .utils import assert_shape, set_seed

__all__ = [
    "DataConfig",
    "EncoderConfig",
    "GateConfig",
    "ExpertConfig",
    "PriorConfig",
    "BaseConfig",
    "TrainConfig",
    "NECConfig",
    "pyramid_dims",
    "FeatureSchema",
    "Batch",
    "SyntheticSpec",
    "Panel",
    "PanelData",
    "SyntheticPanel",
    "SyntheticRegimePanel",
    "expert_log_likelihood",
    "MixtureNLLOutput",
    "mixture_nll",
    "LoadBalanceBuffer",
    "load_balance_aux",
    "expert_decorrelation_aux",
    "correction_penalty_aux",
    "NECModel",
    "NECOutput",
    "RegimePrior",
    "SoftRegimePrior",
    "UniformRegimePrior",
    "HardRegimePrior",
    "TopKRegimePrior",
    "GumbelSoftmaxRegimePrior",
    "HMMRegimePrior",
    "PriorOutput",
    "PriorContext",
    "PRIOR_REGISTRY",
    "build_prior",
    "Router",
    "Trainer",
    "SequenceEval",
    "GradientAudit",
    "DeadParameterWarning",
    "BaseModel",
    "BaseFit",
    "BaseCache",
    "fit_base",
    "base_cache_key",
    "MLPBlock",
    "ACTIVATION_REGISTRY",
    "build_activation",
    "WalkForwardFold",
    "walk_forward_folds",
    "rank_ic_by_date",
    "IcSummary",
    "ic_summary",
    "long_short_by_date",
    "PortfolioSummary",
    "portfolio_summary",
    "FoldResult",
    "WalkForwardResult",
    "walk_forward_evaluate",
    "walk_forward_evaluate_baseline",
    "base_and_correction",
    "BaselineModel",
    "RidgeBaseline",
    "MLPBaseline",
    "Emission",
    "ExpertBank",
    "ClassicalGaussianEmission",
    "EMISSION_REGISTRY",
    "build_emission",
    "StageBSpec",
    "SEQUENCE_FEATURES",
    "SNAPSHOT_FEATURES",
    "build_panel",
    "build_stage_b_panel",
    "rolling_beta",
    "data_config_from_panel",
    "DEFAULT_UNIVERSE",
    "MARKET_SYMBOL",
    "load_ohlcv",
    "load_universe",
    "load_vix",
    "load_french_factors",
    "build_context",
    "gate_utilization_by_date",
    "regime_alignment",
    "gate_regime_alignment",
    "ExpertAlignment",
    "RegimeAlignmentReport",
    "TrialRecord",
    "TrialRegistry",
    "plot_training_dashboard",
    "plot_gate_utilization",
    "plot_ic_series",
    "plot_long_short_curve",
    "plot_transition_matrix",
    "plot_sweep_report",
    "SweepArm",
    "nec_arm",
    "baseline_arm",
    "ArmSummary",
    "SweepReport",
    "run_sweep",
    "corrected_claims",
    "validation_tail",
    "TuneResult",
    "tune",
    "ReliabilityReport",
    "gate_reliability",
    "TemperatureFit",
    "fit_temperature",
    "plot_reliability",
    "PointInTimeUniverse",
    "load_sp500_universe",
    "filter_point_in_time",
    "universe_coverage_report",
    "sharpe_ratio",
    "probabilistic_sharpe_ratio",
    "expected_max_sharpe",
    "DeflatedSharpe",
    "deflated_sharpe_ratio",
    "ic_pvalue",
    "bonferroni",
    "benjamini_hochberg",
    "assert_shape",
    "set_seed",
]
